version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
shallow_clone: true
install:
  - set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
environment:
  matrix:
  - solution_name: GCC Optimizer/GCC Optimizer.csproj
  - solution_name: FlowGraph/FlowGraph.csproj
  - solution_name: GUI/GUI.csproj
build:
  project: '%solution_name%'
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
